include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false

analyzer:
  errors:
    missing_required_param: error
    missing_return: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
  language:
    strict-casts: true
    # strict-raw-types: true
