name: flutter_boilerplate
description: A Boilerplate I made to use
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state managing
  flutter_riverpod: ^2.1.3
  # permission
  permission_handler: ^10.2.0
  # code generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  # env
  flutter_dotenv: ^5.0.2

  # http
  dio: ^4.0.6
  flutter_pretty_dio_logger: ^2.0.3
  # route
  auto_route: ^5.0.4
  # UI
  flutter_screenutil: ^5.6.0

  # notification
  flutter_local_notifications: ^13.0.0
  # locator
  geolocator: ^9.0.2
  # location setting
  intl: ^0.18.0
  # image, camera
  image_picker: ^0.8.6

  # connectivity
  connectivity_plus: ^3.0.2
  # shared preference
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # code generation
  freezed:
  build_runner:
  flutter_gen_runner:
  json_serializable:
  auto_route_generator: ^5.0.3
  # native splash screen
  flutter_native_splash: ^2.2.16
  # sorting import packages
  import_sorter:
  # code metrics
  dart_code_metrics:

  # lint
  flutter_lints: ^2.0.0
  # logger
  logger_fork:
  logger_flutter_fork:

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  #  integrations:
  #    flutter_svg: true
  #    flare_flutter: true
  assets:
    enabled: true
  fonts:
    enabled: true
  images:
    enabled: true
  icons:
    enabled: true

import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/.env.prod
    - assets/env/.env.dev
    - assets/env/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/
